# Generated by Django 5.0.1 on 2024-01-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_nbap_delete_nbat'),
    ]

    operations = [
        migrations.CreateModel(
            name='hala',
            fields=[
                ('id_hala', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_hali', models.CharField(max_length=30)),
                ('pojemnosc', models.CharField(max_length=30)),
                ('miasto', models.CharField(max_length=10)),
                ('kod_pocztowy', models.CharField(max_length=15)),
                ('adres', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='klub',
            fields=[
                ('id_klub', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa_druzyny', models.CharField(max_length=30)),
                ('miasto', models.CharField(max_length=20)),
                ('konferencja', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='liga_nba',
            fields=[
                ('id_liga', models.AutoField(primary_key=True, serialize=False)),
                ('ilosc_zespolow', models.CharField(max_length=10)),
                ('kraj', models.CharField(max_length=20)),
                ('puchar', models.CharField(max_length=15)),
                ('sezon', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='mecz',
            fields=[
                ('id_mecz', models.AutoField(primary_key=True, serialize=False)),
                ('id_gosc', models.CharField(max_length=30)),
                ('id_gospodarz', models.CharField(max_length=20)),
                ('wynik', models.CharField(max_length=10)),
                ('lokalizacja', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='statystyki',
            fields=[
                ('id_statystyki', models.CharField(max_length=30)),
                ('punkty', models.AutoField(primary_key=True, serialize=False)),
                ('zbiorki', models.CharField(max_length=10)),
                ('bloki', models.CharField(max_length=20)),
                ('przechwyty', models.CharField(max_length=15)),
                ('wygrane', models.CharField(max_length=8)),
                ('przegrane', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='trener',
            fields=[
                ('id_trener', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('data_urodzenia', models.CharField(max_length=20)),
                ('narodowosc', models.CharField(max_length=15)),
                ('staz_w_druzynie', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='zawodnicy',
            fields=[
                ('id_zawodnicy', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=10)),
                ('nazwisko', models.CharField(max_length=20)),
                ('narodowosc', models.CharField(max_length=15)),
                ('wzrost', models.CharField(max_length=8)),
                ('data_urodzenia', models.CharField()),
                ('waga', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='NBAP',
        ),
    ]
