# Generated by Django 5.0.1 on 2024-01-17 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_zawodnicy_druzyna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zawodnicy',
            name='druzyna',
        ),
        migrations.AddField(
            model_name='trener',
            name='klub',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MyApp.klub'),
        ),
        migrations.AddField(
            model_name='zawodnicy',
            name='klub',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MyApp.klub'),
        ),
    ]
