# Generated by Django 5.0.1 on 2024-01-17 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_remove_zawodnicy_druzyna_trener_klub_zawodnicy_klub'),
    ]

    operations = [
        migrations.AddField(
            model_name='hala',
            name='klub',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MyApp.klub'),
        ),
    ]
